name: ${name}
main: ${package}.${name}
version: ${version}
author: KaiNoMood
depend: [GriefPreventionPlus, WorldEdit]

commands:
   GPPSkyBlock:
      description: ${name} main command
      aliases: [island, is]

permissions:
    gppskyblock.spawn:
        default: true
    gppskyblock.reset:
        default: true
    gppskyblock.setspawn:
        default: true
    gppskyblock.setbiome.all:
        default: false
    gppskyblock.manage:
        default: op
    gppskyblock.setradius:
        default: op
    gppskyblock.override:
        default: op
    gppskyblock.leaveisland:
        default: true
